### ISSUE TITLE
[App - Virtual Tutor] Speech to text && Text to speech && Speech to speech

### ISSUE THREAD

**Issue by iarandrd** [ErasmusEgalitarian/educado-mobile#367]
The user can talk to the chatbot and the chatbot will answer in text. (Because in Brazil it's very common to send voice messages to each other). 
TTS && STS is less important than the other ones.

**Comment by DomoMKT** [comment]
you're looking for a reliable way to convert text to speech with low latency? try [www.nemesyslabs.com](https://www.nemesyslabs.com) and you'll find what you need!
