### ISSUE TITLE
Inconsistent Component Naming in `Register.js`

### ISSUE THREAD

**Issue by ITPini** [ErasmusEgalitarian/educado-mobile#94]
## Issue Description

The main component in the `Register.js` file is named `LoginForm`, which is misleading. The name suggests it's a component for logging in, but its purpose is to allow users to register.

## Steps to Reproduce

1. Navigate to `eml/components/login/RegisterForm.js`.
2. Observe the main component's name:
https://github.com/Educado-App/educado-mobile/blob/21ae5c9d759eb0cff05baa523231a78a06506f9a/eml/components/login/RegisterForm.js#L24
(also this component have an unused props parameter)

## Expected Behavior

The component should be named appropriately to reflect its purpose, such as `RegisterForm`.

## Actual Behavior

The component in the `Register.js` file is misleadingly named `LoginForm`.

## Additional Information

- **Environment**: Mobile

**Comment by MortenMunk** [comment]
This is fixed on dev now 😄
